name = "praise-api"
main = "index.js"
compatibility_date = "2024-10-23"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "__BUCKET_NAME__"
preview_bucket_name = "__BUCKET_NAME__"

# routes 应该在顶级配置中
[[routes]]
pattern = "__API_DOMAIN__/*"
zone_name = "__ZONE_NAME__"
