name = "my-mp3-api"
main = "index.js"
compatibility_date = "2024-10-23"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "jiamingzh"
preview_bucket_name = "jiamingzh"

routes = [
  { pattern = "mapi.ours24.dpdns.org/*", zone_name = "ours24.dpdns.org" }
]
